ninapro_db1_subjects = 27
ninapro_db1_num_gestures = 53
ninapro_db1_num_repetitions = 10
ninapro_db1_fs = 100

ninapro_db1_gesture_labels = [
    'Rest',
    'Index flexion',
    'Index extension',
    'Middle flexion',
    'Middle extension',
    'Ring flexion',
    'Ring extension',
    'Little finger flexion',
    'Little finger extension',
    'Thumb adduction',
    'Thumb abduction',
    'Thumb flexion',
    'Thumb extension',
    'Thumb up',
    'Extension of index and middle, flexion of the others',
    'Flexion of ring and little finger, extension of the others',
    'Thumb opposing base of little finger',
    'Abduction of all fingers',
    'Fingers flexed together in fist',
    'Pointing index',
    'Adduction of extended fingers',
    'Wrist supination (axis: middle finger)',
    'Wrist pronation (axis: middle finger)',
    'Wrist supination (axis: little finger)',
    'Wrist pronation (axis: little finger)',
    'Wrist flexion',
    'Wrist extension',
    'Wrist radial deviation',
    'Wrist ulnar deviation',
    'Wrist extension with closed hand',
    'Large diameter grasp',
    'Small diameter grasp (power grip)',
    'Fixed hook grasp',
    'Index finger extension grasp',
    'Medium wrap',
    'Ring grasp',
    'Prismatic four fingers grasp',
    'Stick grasp',
    'Writing tripod grasp',
    'Power sphere grasp',
    'Three finger sphere grasp',
    'Precision sphere grasp',
    'Tripod grasp',
    'Prismatic pinch grasp',
    'Tip pinch grasp',
    'Quadpod grasp',
    'Lateral grasp',
    'Parallel extension grasp',
    'Extension type grasp',
    'Power disk grasp',
    'Open a bottle with a tripod grasp',
    'Turn a screw (grasp the screwdriver with a stick grasp)',
    'Cut something (grasp the knife with an index finger extension grasp)'
]

